export const TEST_IDS = {
  signIn: {
    form: 'sign-in-form',
    emailInput: 'sign-in-email-input',
    passwordInput: 'sign-in-password-input',
    submit: 'sign-in-submit',
    error: 'sign-in-error',
  },
  menu: {
    toggle: 'menu-toggle',
    close: 'menu-close',
    backdrop: 'menu-backdrop',
    panel: 'menu-panel',
    dictionarySelect: 'menu-dictionary-select',
    randomToggle: 'menu-random-toggle',
    learningToggle: 'menu-learning-toggle',
    settingsOpen: 'menu-settings-open',
    addWord: 'menu-add-word',
    signOut: 'menu-signout',
  },
  search: {
    input: 'search-input',
    addPlus: 'search-add-plus',
    suggestionItem: 'search-suggestion-item',
  },
  nav: {
    previous: 'nav-previous',
    next: 'nav-next',
  },
  word: {
    title: 'word-title',
    translation: 'word-translation',
  },
  learning: {
    showTranslation: 'learning-show-translation',
  },
  sentence: {
    generateButton: 'generate-sentence-button',
    text: 'generated-sentence-text',
  },
  addWord: {
    modal: 'add-word-modal',
    wordInput: 'add-word-input',
    translationInput: 'add-word-translation-input',
    dictionarySelect: 'add-word-dictionary-select',
    submit: 'add-word-submit',
    close: 'add-word-close',
    success: 'add-word-success',
    error: 'add-word-error',
  },
  settings: {
    modal: 'settings-modal',
    close: 'settings-close',
    languageLevelSelect: 'settings-language-level-select',
    themeToggle: 'settings-theme-toggle',
    hideSentenceToggle: 'settings-hide-sentence-toggle',
    historyOpen: 'settings-history-open',
    reset: 'settings-reset',
    topicSelect: 'settings-topic-select',
    addDictionary: 'settings-add-dictionary',
  },
  history: {
    modal: 'history-modal',
    clear: 'history-clear',
    close: 'history-close',
    item: 'history-item',
    empty: 'history-empty',
  },
  addDictionary: {
    modal: 'add-dictionary-modal',
    titleInput: 'add-dictionary-title-input',
    languageInput: 'add-dictionary-language-input',
    submit: 'add-dictionary-submit',
    close: 'add-dictionary-close',
    success: 'add-dictionary-success',
    error: 'add-dictionary-error',
  },
};
